name: PR Review

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: yarn
      - name: Build
        run: |
          yarn build
          yarn types
      - name: Run Tests
        run: yarn test
      - name: Lint Code
        run: yarn lint
